name:                in-other-words
version:             0.2.1.0
synopsis:            A higher-order effect system where the sky's the limit
description:
  A low-boilerplate effect system with easy higher-order effects and very high expressive power
homepage:            https://github.com/KingoftheHomeless/in-other-words#readme
license:             BSD3
author:              Love Waern
maintainer:          combiner8761@gmail.com
copyright:           BSD3
category:            Control
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
  - base >= 4.7 && < 5
  - async >= 2.2 && < 2.3
  - transformers >= 0.5.6 && < 0.6
  - mtl >= 2.2 && < 2.3
  - monad-control >= 1.0 && < 1.1
  - transformers-base >= 0.4.5 && < 0.5
  - exceptions >= 0.10 && < 0.11
  - stm >= 2.5 && < 2.6
  - th-abstraction >= 0.3 && < 0.5
  - template-haskell >= 2.15 && < 2.19
  - syb >= 0.7 && < 0.8
  - containers >= 0.6 && < 0.7

library:
  ghc-options: -Wall -haddock
  source-dirs: src

tests:
  in-other-words-test:
    main:                Main.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O0

    build-tools:
    - hspec-discover >= 2.0
    dependencies:
    - in-other-words
    - hspec >= 2.6.0 && < 3

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DerivingStrategies
  - EmptyCase
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - PolyKinds
  - QuantifiedConstraints
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeApplications
  - TypeOperators
  - TypeFamilies
  - UndecidableInstances
